modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "extendedflywheels"
version = "${version}"
displayName = "Extended Flywheels"
authors = "Rabbitminers"
description = '''
A simple mod to enhance building with create.
'''
logoFile = "icon.png"

[[dependencies.extendedflywheels]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedflywheels]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedflywheels]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"